'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class resEspañol
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Capa3_Seguridad_Servicios.resEspañol", GetType(resEspañol).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administrar Clientes.
        '''</summary>
        Friend Shared ReadOnly Property ABMCliente() As String
            Get
                Return ResourceManager.GetString("ABMCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administrar Familia.
        '''</summary>
        Friend Shared ReadOnly Property ABMFamilia() As String
            Get
                Return ResourceManager.GetString("ABMFamilia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administrar Patente.
        '''</summary>
        Friend Shared ReadOnly Property ABMPatente() As String
            Get
                Return ResourceManager.GetString("ABMPatente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administrar Usuario.
        '''</summary>
        Friend Shared ReadOnly Property ABMUsuario() As String
            Get
                Return ResourceManager.GetString("ABMUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aceptar.
        '''</summary>
        Friend Shared ReadOnly Property Aceptar() As String
            Get
                Return ResourceManager.GetString("Aceptar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Acerca de ...
        '''</summary>
        Friend Shared ReadOnly Property Acercade() As String
            Get
                Return ResourceManager.GetString("Acercade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Estado: Activado.
        '''</summary>
        Friend Shared ReadOnly Property Activado() As String
            Get
                Return ResourceManager.GetString("Activado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Activar.
        '''</summary>
        Friend Shared ReadOnly Property Activar() As String
            Get
                Return ResourceManager.GetString("Activar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Actualizar.
        '''</summary>
        Friend Shared ReadOnly Property Actualizar() As String
            Get
                Return ResourceManager.GetString("Actualizar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administracion.
        '''</summary>
        Friend Shared ReadOnly Property Administracion() As String
            Get
                Return ResourceManager.GetString("Administracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administrar Base de Datos.
        '''</summary>
        Friend Shared ReadOnly Property AdministrarBD() As String
            Get
                Return ResourceManager.GetString("AdministrarBD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Agregar &gt;&gt;.
        '''</summary>
        Friend Shared ReadOnly Property Agregar() As String
            Get
                Return ResourceManager.GetString("Agregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;&lt; Anterior.
        '''</summary>
        Friend Shared ReadOnly Property Anterior() As String
            Get
                Return ResourceManager.GetString("Anterior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Apellido.
        '''</summary>
        Friend Shared ReadOnly Property Apellido() As String
            Get
                Return ResourceManager.GetString("Apellido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Asignar .
        '''</summary>
        Friend Shared ReadOnly Property Asignar() As String
            Get
                Return ResourceManager.GetString("Asignar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Automático.
        '''</summary>
        Friend Shared ReadOnly Property Automatico() As String
            Get
                Return ResourceManager.GetString("Automatico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ayuda.
        '''</summary>
        Friend Shared ReadOnly Property Ayuda() As String
            Get
                Return ResourceManager.GetString("Ayuda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Respaldar.
        '''</summary>
        Friend Shared ReadOnly Property Backup() As String
            Get
                Return ResourceManager.GetString("Backup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Barra de Estado.
        '''</summary>
        Friend Shared ReadOnly Property BEstado() As String
            Get
                Return ResourceManager.GetString("BEstado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Barra de Herramientas.
        '''</summary>
        Friend Shared ReadOnly Property BHerramientas() As String
            Get
                Return ResourceManager.GetString("BHerramientas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Bitacora.
        '''</summary>
        Friend Shared ReadOnly Property Bitacora() As String
            Get
                Return ResourceManager.GetString("Bitacora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Buscar.
        '''</summary>
        Friend Shared ReadOnly Property Buscar() As String
            Get
                Return ResourceManager.GetString("Buscar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Buscar Estado de Cheques de Cliente.
        '''</summary>
        Friend Shared ReadOnly Property Buscar_Estado() As String
            Get
                Return ResourceManager.GetString("Buscar_Estado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Buscar Cheque.
        '''</summary>
        Friend Shared ReadOnly Property BuscarCheque() As String
            Get
                Return ResourceManager.GetString("BuscarCheque", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Beneficiario.
        '''</summary>
        Friend Shared ReadOnly Property C_Benef() As String
            Get
                Return ResourceManager.GetString("C_Benef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Categoría.
        '''</summary>
        Friend Shared ReadOnly Property C_Categoria() As String
            Get
                Return ResourceManager.GetString("C_Categoria", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Cobrado.
        '''</summary>
        Friend Shared ReadOnly Property C_Cob() As String
            Get
                Return ResourceManager.GetString("C_Cob", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Comisión.
        '''</summary>
        Friend Shared ReadOnly Property C_Comision() As String
            Get
                Return ResourceManager.GetString("C_Comision", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Fecha de Emsion.
        '''</summary>
        Friend Shared ReadOnly Property C_FechaEmi() As String
            Get
                Return ResourceManager.GetString("C_FechaEmi", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Importe.
        '''</summary>
        Friend Shared ReadOnly Property C_Importe() As String
            Get
                Return ResourceManager.GetString("C_Importe", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Importe en Letras.
        '''</summary>
        Friend Shared ReadOnly Property C_Importe_Letra() As String
            Get
                Return ResourceManager.GetString("C_Importe_Letra", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Motivo.
        '''</summary>
        Friend Shared ReadOnly Property C_Motivo() As String
            Get
                Return ResourceManager.GetString("C_Motivo", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Multa.
        '''</summary>
        Friend Shared ReadOnly Property C_Multa() As String
            Get
                Return ResourceManager.GetString("C_Multa", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Nro. de Serie.
        '''</summary>
        Friend Shared ReadOnly Property C_NroSerie() As String
            Get
                Return ResourceManager.GetString("C_NroSerie", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Rechazado.
        '''</summary>
        Friend Shared ReadOnly Property C_Rech() As String
            Get
                Return ResourceManager.GetString("C_Rech", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Fecha de Rechazo.
        '''</summary>
        Friend Shared ReadOnly Property C_Rech_Fecha() As String
            Get
                Return ResourceManager.GetString("C_Rech_Fecha", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Rechazado/Cobrado.
        '''</summary>
        Friend Shared ReadOnly Property C_RechCobr() As String
            Get
                Return ResourceManager.GetString("C_RechCobr", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Recibido.
        '''</summary>
        Friend Shared ReadOnly Property C_Recib() As String
            Get
                Return ResourceManager.GetString("C_Recib", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Fecha de Recibimiento.
        '''</summary>
        Friend Shared ReadOnly Property C_Recib_Fecha() As String
            Get
                Return ResourceManager.GetString("C_Recib_Fecha", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Cambiar Contraseña.
        '''</summary>
        Friend Shared ReadOnly Property Cambiar() As String
            Get
                Return ResourceManager.GetString("Cambiar", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Cancelar.
        '''</summary>
        Friend Shared ReadOnly Property Cancelar() As String
            Get
                Return ResourceManager.GetString("Cancelar", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Cancelar Nuevo.
        '''</summary>
        Friend Shared ReadOnly Property Cancelar_Nuevo() As String
            Get
                Return ResourceManager.GetString("Cancelar_Nuevo", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Cargo.
        '''</summary>
        Friend Shared ReadOnly Property Cargo() As String
            Get
                Return ResourceManager.GetString("Cargo", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Cascada.
        '''</summary>
        Friend Shared ReadOnly Property Cascada() As String
            Get
                Return ResourceManager.GetString("Cascada", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Categorías.
        '''</summary>
        Friend Shared ReadOnly Property Categorias() As String
            Get
                Return ResourceManager.GetString("Categorias", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Cerrar.
        '''</summary>
        Friend Shared ReadOnly Property Cerrar() As String
            Get
                Return ResourceManager.GetString("Cerrar", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Cerrar Sesion.
        '''</summary>
        Friend Shared ReadOnly Property Cerrar_Sesion() As String
            Get
                Return ResourceManager.GetString("Cerrar_Sesion", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Del Cliente.
        '''</summary>
        Friend Shared ReadOnly Property CheckCliente() As String
            Get
                Return ResourceManager.GetString("CheckCliente", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a No del Cliente.
        '''</summary>
        Friend Shared ReadOnly Property CheckNoCliente() As String
            Get
                Return ResourceManager.GetString("CheckNoCliente", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Cheque Cobrado.
        '''</summary>
        Friend Shared ReadOnly Property Cheque_C() As String
            Get
                Return ResourceManager.GetString("Cheque_C", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Clientes.
        '''</summary>
        Friend Shared ReadOnly Property Cliente() As String
            Get
                Return ResourceManager.GetString("Cliente", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Cobrar Cheque.
        '''</summary>
        Friend Shared ReadOnly Property Cobrar_Cheque() As String
            Get
                Return ResourceManager.GetString("Cobrar_Cheque", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a ID Cheque.
        '''</summary>
        Friend Shared ReadOnly Property Cod_Cheque() As String
            Get
                Return ResourceManager.GetString("Cod_Cheque", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Código de Cuenta.
        '''</summary>
        Friend Shared ReadOnly Property Cod_Cuenta() As String
            Get
                Return ResourceManager.GetString("Cod_Cuenta", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Código Postal.
        '''</summary>
        Friend Shared ReadOnly Property Cod_Post() As String
            Get
                Return ResourceManager.GetString("Cod_Post", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Comentarios.
        '''</summary>
        Friend Shared ReadOnly Property Comentarios() As String
            Get
                Return ResourceManager.GetString("Comentarios", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Comision.
        '''</summary>
        Friend Shared ReadOnly Property Comision() As String
            Get
                Return ResourceManager.GetString("Comision", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Comprimir.
        '''</summary>
        Friend Shared ReadOnly Property Comprimir() As String
            Get
                Return ResourceManager.GetString("Comprimir", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Comprobante.
        '''</summary>
        Friend Shared ReadOnly Property Comprobante() As String
            Get
                Return ResourceManager.GetString("Comprobante", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Concepto.
        '''</summary>
        Friend Shared ReadOnly Property Concepto() As String
            Get
                Return ResourceManager.GetString("Concepto", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Condición.
        '''</summary>
        Friend Shared ReadOnly Property Condicion() As String
            Get
                Return ResourceManager.GetString("Condicion", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Configuraciones.
        '''</summary>
        Friend Shared ReadOnly Property Configuraciones() As String
            Get
                Return ResourceManager.GetString("Configuraciones", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Consulta.
        '''</summary>
        Friend Shared ReadOnly Property Consulta() As String
            Get
                Return ResourceManager.GetString("Consulta", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Contenido.
        '''</summary>
        Friend Shared ReadOnly Property Contenido() As String
            Get
                Return ResourceManager.GetString("Contenido", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Contraseña.
        '''</summary>
        Friend Shared ReadOnly Property Contrasena() As String
            Get
                Return ResourceManager.GetString("Contrasena", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Controles.
        '''</summary>
        Friend Shared ReadOnly Property Controles() As String
            Get
                Return ResourceManager.GetString("Controles", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Copiar.
        '''</summary>
        Friend Shared ReadOnly Property Copiar() As String
            Get
                Return ResourceManager.GetString("Copiar", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Costo.
        '''</summary>
        Friend Shared ReadOnly Property Costo() As String
            Get
                Return ResourceManager.GetString("Costo", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Criticidad.
        '''</summary>
        Friend Shared ReadOnly Property Criticidad() As String
            Get
                Return ResourceManager.GetString("Criticidad", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Estado: Desactivado.
        '''</summary>
        Friend Shared ReadOnly Property Desactivado() As String
            Get
                Return ResourceManager.GetString("Desactivado", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Desactivar.
        '''</summary>
        Friend Shared ReadOnly Property Desactivar() As String
            Get
                Return ResourceManager.GetString("Desactivar", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Descripcion.
        '''</summary>
        Friend Shared ReadOnly Property Descripcion() As String
            Get
                Return ResourceManager.GetString("Descripcion", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Desde.
        '''</summary>
        Friend Shared ReadOnly Property Desde() As String
            Get
                Return ResourceManager.GetString("Desde", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Detalle.
        '''</summary>
        Friend Shared ReadOnly Property Detalle() As String
            Get
                Return ResourceManager.GetString("Detalle", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Detalles de Cuenta Corriente.
        '''</summary>
        Friend Shared ReadOnly Property DetallesCuenta() As String
            Get
                Return ResourceManager.GetString("DetallesCuenta", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Detalle de Ventas.
        '''</summary>
        Friend Shared ReadOnly Property DetalleVentas() As String
            Get
                Return ResourceManager.GetString("DetalleVentas", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Direccion.
        '''</summary>
        Friend Shared ReadOnly Property Direccion() As String
            Get
                Return ResourceManager.GetString("Direccion", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Dígito Verificador.
        '''</summary>
        Friend Shared ReadOnly Property DV() As String
            Get
                Return ResourceManager.GetString("DV", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Edad.
        '''</summary>
        Friend Shared ReadOnly Property Edad() As String
            Get
                Return ResourceManager.GetString("Edad", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Eliminar.
        '''</summary>
        Friend Shared ReadOnly Property Eliminar() As String
            Get
                Return ResourceManager.GetString("Eliminar", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a E-Mail.
        '''</summary>
        Friend Shared ReadOnly Property EMail() As String
            Get
                Return ResourceManager.GetString("EMail", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Empleados.
        '''</summary>
        Friend Shared ReadOnly Property Empleado() As String
            Get
                Return ResourceManager.GetString("Empleado", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Contacte al Administrador del Sistema.
        '''</summary>
        Friend Shared ReadOnly Property Err_Adm() As String
            Get
                Return ResourceManager.GetString("Err_Adm", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Se ha detectado un error en la Base de Datos. Tabla/Registro :.
        '''</summary>
        Friend Shared ReadOnly Property Err_BD() As String
            Get
                Return ResourceManager.GetString("Err_BD", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Campo en Blanco: .
        '''</summary>
        Friend Shared ReadOnly Property Err_Blanco() As String
            Get
                Return ResourceManager.GetString("Err_Blanco", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a No se encuentra una coincidencia según el campo:.
        '''</summary>
        Friend Shared ReadOnly Property Err_Busqueda() As String
            Get
                Return ResourceManager.GetString("Err_Busqueda", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a El Formato No es Válido o del Tipo Esperado para el campo :.
        '''</summary>
        Friend Shared ReadOnly Property Err_Campo() As String
            Get
                Return ResourceManager.GetString("Err_Campo", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a La cantidad debe ser mayor a 1.
        '''</summary>
        Friend Shared ReadOnly Property Err_Cantidad() As String
            Get
                Return ResourceManager.GetString("Err_Cantidad", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a No se puede realizar la operación debido a que la base de datos está abierta. Consulte al administrador.
        '''</summary>
        Friend Shared ReadOnly Property Err_Conexion() As String
            Get
                Return ResourceManager.GetString("Err_Conexion", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Error al Eliminar Familia.
        '''</summary>
        Friend Shared ReadOnly Property Err_Elim_Fam() As String
            Get
                Return ResourceManager.GetString("Err_Elim_Fam", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Ya existe:.
        '''</summary>
        Friend Shared ReadOnly Property Err_Existe() As String
            Get
                Return ResourceManager.GetString("Err_Existe", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a La nueva contraseña no coincide, ingresela nuevamente.
        '''</summary>
        Friend Shared ReadOnly Property Err_PassN() As String
            Get
                Return ResourceManager.GetString("Err_PassN", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Su contraseña actual no coincide.
        '''</summary>
        Friend Shared ReadOnly Property Err_PassV() As String
            Get
                Return ResourceManager.GetString("Err_PassV", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Se ha Detectado un Error al Leer/Escribir en la Base de Datos. Consulte al Administrador.
        '''</summary>
        Friend Shared ReadOnly Property Err_SQL() As String
            Get
                Return ResourceManager.GetString("Err_SQL", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a El usuario ya pertenece a una familia.
        '''</summary>
        Friend Shared ReadOnly Property Err_Usu_Fam() As String
            Get
                Return ResourceManager.GetString("Err_Usu_Fam", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Ya existe en la base un Usuario con el Nombre : .
        '''</summary>
        Friend Shared ReadOnly Property Err_Usuario() As String
            Get
                Return ResourceManager.GetString("Err_Usuario", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Error en la Seleccion de Contraseña. Por favor reingresela.
        '''</summary>
        Friend Shared ReadOnly Property Error_Reing_Pass() As String
            Get
                Return ResourceManager.GetString("Error_Reing_Pass", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Error No Definido.
        '''</summary>
        Friend Shared ReadOnly Property Error1() As String
            Get
                Return ResourceManager.GetString("Error1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a ¿ Está seguro de que desea cerrar el formulario ?.
        '''</summary>
        Friend Shared ReadOnly Property Esperar() As String
            Get
                Return ResourceManager.GetString("Esperar", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Estado.
        '''</summary>
        Friend Shared ReadOnly Property Estado() As String
            Get
                Return ResourceManager.GetString("Estado", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Evento.
        '''</summary>
        Friend Shared ReadOnly Property Evento() As String
            Get
                Return ResourceManager.GetString("Evento", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Examinar.
        '''</summary>
        Friend Shared ReadOnly Property Examinar() As String
            Get
                Return ResourceManager.GetString("Examinar", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Operación Exitosa.
        '''</summary>
        Friend Shared ReadOnly Property Exito() As String
            Get
                Return ResourceManager.GetString("Exito", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Familias.
        '''</summary>
        Friend Shared ReadOnly Property Familia() As String
            Get
                Return ResourceManager.GetString("Familia", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Fecha.
        '''</summary>
        Friend Shared ReadOnly Property Fecha() As String
            Get
                Return ResourceManager.GetString("Fecha", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Fecha de Ingreso.
        '''</summary>
        Friend Shared ReadOnly Property Fecha_Ing() As String
            Get
                Return ResourceManager.GetString("Fecha_Ing", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Fecha de Nacimiento.
        '''</summary>
        Friend Shared ReadOnly Property Fecha_Nac() As String
            Get
                Return ResourceManager.GetString("Fecha_Nac", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Finanzas.
        '''</summary>
        Friend Shared ReadOnly Property Finanzas() As String
            Get
                Return ResourceManager.GetString("Finanzas", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Hasta.
        '''</summary>
        Friend Shared ReadOnly Property Hasta() As String
            Get
                Return ResourceManager.GetString("Hasta", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Herramientas.
        '''</summary>
        Friend Shared ReadOnly Property Herramientas() As String
            Get
                Return ResourceManager.GetString("Herramientas", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Hora.
        '''</summary>
        Friend Shared ReadOnly Property Hora() As String
            Get
                Return ResourceManager.GetString("Hora", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Horizontal.
        '''</summary>
        Friend Shared ReadOnly Property Horizontal() As String
            Get
                Return ResourceManager.GetString("Horizontal", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Código.
        '''</summary>
        Friend Shared ReadOnly Property ID() As String
            Get
                Return ResourceManager.GetString("ID", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Cambiar Idioma.
        '''</summary>
        Friend Shared ReadOnly Property Idioma_Cambiar() As String
            Get
                Return ResourceManager.GetString("Idioma_Cambiar", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Idioma.
        '''</summary>
        Friend Shared ReadOnly Property Idioma_Text() As String
            Get
                Return ResourceManager.GetString("Idioma_Text", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Imprimir.
        '''</summary>
        Friend Shared ReadOnly Property Imprimir() As String
            Get
                Return ResourceManager.GetString("Imprimir", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Indice.
        '''</summary>
        Friend Shared ReadOnly Property Indice() As String
            Get
                Return ResourceManager.GetString("Indice", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Ingresos.
        '''</summary>
        Friend Shared ReadOnly Property Ingresos() As String
            Get
                Return ResourceManager.GetString("Ingresos", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Iniciar Sesion.
        '''</summary>
        Friend Shared ReadOnly Property Iniciar_Sesion() As String
            Get
                Return ResourceManager.GetString("Iniciar_Sesion", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Limpiar.
        '''</summary>
        Friend Shared ReadOnly Property Limpiar() As String
            Get
                Return ResourceManager.GetString("Limpiar", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Listado de Cheques.
        '''</summary>
        Friend Shared ReadOnly Property Listado_Cheque() As String
            Get
                Return ResourceManager.GetString("Listado_Cheque", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Listar.
        '''</summary>
        Friend Shared ReadOnly Property Listar() As String
            Get
                Return ResourceManager.GetString("Listar", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Localidad.
        '''</summary>
        Friend Shared ReadOnly Property Localidad() As String
            Get
                Return ResourceManager.GetString("Localidad", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Miembro De:.
        '''</summary>
        Friend Shared ReadOnly Property MiembroDe() As String
            Get
                Return ResourceManager.GetString("MiembroDe", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Monto.
        '''</summary>
        Friend Shared ReadOnly Property Monto() As String
            Get
                Return ResourceManager.GetString("Monto", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Escriba el motivo de rechazo del cheque:.
        '''</summary>
        Friend Shared ReadOnly Property Motivo_Preg() As String
            Get
                Return ResourceManager.GetString("Motivo_Preg", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Apodo.
        '''</summary>
        Friend Shared ReadOnly Property Nick() As String
            Get
                Return ResourceManager.GetString("Nick", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Nombre.
        '''</summary>
        Friend Shared ReadOnly Property Nombre() As String
            Get
                Return ResourceManager.GetString("Nombre", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Nuevo.
        '''</summary>
        Friend Shared ReadOnly Property Nuevo() As String
            Get
                Return ResourceManager.GetString("Nuevo", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Numero.
        '''</summary>
        Friend Shared ReadOnly Property Numero() As String
            Get
                Return ResourceManager.GetString("Numero", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Ocupación.
        '''</summary>
        Friend Shared ReadOnly Property Ocupacion() As String
            Get
                Return ResourceManager.GetString("Ocupacion", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Backup se realizo con éxito.
        '''</summary>
        Friend Shared ReadOnly Property OK_Backup() As String
            Get
                Return ResourceManager.GetString("OK_Backup", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a ¿ Esta seguro de Cambiar el Idioma ?.
        '''</summary>
        Friend Shared ReadOnly Property OK_Idioma() As String
            Get
                Return ResourceManager.GetString("OK_Idioma", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a ¿ Esta Seguro que desea cambiar la Contraseña ?.
        '''</summary>
        Friend Shared ReadOnly Property OK_Password() As String
            Get
                Return ResourceManager.GetString("OK_Password", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Restauracion Satisfactoria.
        '''</summary>
        Friend Shared ReadOnly Property OK_Restore() As String
            Get
                Return ResourceManager.GetString("OK_Restore", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Opciones.
        '''</summary>
        Friend Shared ReadOnly Property Opciones() As String
            Get
                Return ResourceManager.GetString("Opciones", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Pais.
        '''</summary>
        Friend Shared ReadOnly Property Pais() As String
            Get
                Return ResourceManager.GetString("Pais", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Contraseña Nueva:.
        '''</summary>
        Friend Shared ReadOnly Property Pass_Nuevo() As String
            Get
                Return ResourceManager.GetString("Pass_Nuevo", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Contraseña Actual:.
        '''</summary>
        Friend Shared ReadOnly Property Pass_viejo() As String
            Get
                Return ResourceManager.GetString("Pass_viejo", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Patentes.
        '''</summary>
        Friend Shared ReadOnly Property Patentes() As String
            Get
                Return ResourceManager.GetString("Patentes", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a ¿Está seguro?.
        '''</summary>
        Friend Shared ReadOnly Property Preg_Opera() As String
            Get
                Return ResourceManager.GetString("Preg_Opera", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Busca una cadena traducida similar a Previsualizar.
        '''</summary>
        Friend Shared ReadOnly Property Preview() As String
            Get
                Return ResourceManager.GetString("Preview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Procesos.
        '''</summary>
        Friend Shared ReadOnly Property Procesos() As String
            Get
                Return ResourceManager.GetString("Procesos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Productos.
        '''</summary>
        Friend Shared ReadOnly Property Productos() As String
            Get
                Return ResourceManager.GetString("Productos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Provincia.
        '''</summary>
        Friend Shared ReadOnly Property Provincia() As String
            Get
                Return ResourceManager.GetString("Provincia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Este es un proyecto desarrollado para la cátedra de Trabajo de Diploma I, En la carrera de Ingeniería en Sistemas Informáticos para la facultad Universidad Abierta Interamericana..
        '''</summary>
        Friend Shared ReadOnly Property Proyecto() As String
            Get
                Return ResourceManager.GetString("Proyecto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sistema de Compra y Venta. Prohibida su distribución sin el consentimiento a la empresa creadora..
        '''</summary>
        Friend Shared ReadOnly Property PurchaseAndSell() As String
            Get
                Return ResourceManager.GetString("PurchaseAndSell", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;&lt; Quitar.
        '''</summary>
        Friend Shared ReadOnly Property Quitar() As String
            Get
                Return ResourceManager.GetString("Quitar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Registrar.
        '''</summary>
        Friend Shared ReadOnly Property Registrar() As String
            Get
                Return ResourceManager.GetString("Registrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Registro de Ventas.
        '''</summary>
        Friend Shared ReadOnly Property RegistroVentas() As String
            Get
                Return ResourceManager.GetString("RegistroVentas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reingrese Contraseña:.
        '''</summary>
        Friend Shared ReadOnly Property Rein_Pass() As String
            Get
                Return ResourceManager.GetString("Rein_Pass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Se ha realizado la reparacion de la BD.
        '''</summary>
        Friend Shared ReadOnly Property ReparacionBD() As String
            Get
                Return ResourceManager.GetString("ReparacionBD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reporte de .
        '''</summary>
        Friend Shared ReadOnly Property Reporte() As String
            Get
                Return ResourceManager.GetString("Reporte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reporte de Empleados.
        '''</summary>
        Friend Shared ReadOnly Property ReporteEmpleados() As String
            Get
                Return ResourceManager.GetString("ReporteEmpleados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reporte de Productos.
        '''</summary>
        Friend Shared ReadOnly Property ReporteProductos() As String
            Get
                Return ResourceManager.GetString("ReporteProductos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reportes.
        '''</summary>
        Friend Shared ReadOnly Property Reportes() As String
            Get
                Return ResourceManager.GetString("Reportes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reserva.
        '''</summary>
        Friend Shared ReadOnly Property Reserva() As String
            Get
                Return ResourceManager.GetString("Reserva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Restaurar.
        '''</summary>
        Friend Shared ReadOnly Property Restore() As String
            Get
                Return ResourceManager.GetString("Restore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Salir.
        '''</summary>
        Friend Shared ReadOnly Property Salir() As String
            Get
                Return ResourceManager.GetString("Salir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Seguridad.
        '''</summary>
        Friend Shared ReadOnly Property Seguridad() As String
            Get
                Return ResourceManager.GetString("Seguridad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Seleccionar.
        '''</summary>
        Friend Shared ReadOnly Property Seleccionar() As String
            Get
                Return ResourceManager.GetString("Seleccionar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dirección de Sucursal.
        '''</summary>
        Friend Shared ReadOnly Property SucursalDir() As String
            Get
                Return ResourceManager.GetString("SucursalDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Número de Sucursal.
        '''</summary>
        Friend Shared ReadOnly Property SucursalNro() As String
            Get
                Return ResourceManager.GetString("SucursalNro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Telefono.
        '''</summary>
        Friend Shared ReadOnly Property Telefono() As String
            Get
                Return ResourceManager.GetString("Telefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tipo de Teléfono.
        '''</summary>
        Friend Shared ReadOnly Property TipoTel() As String
            Get
                Return ResourceManager.GetString("TipoTel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Seleccione donde desea guardar la copia de seguridad.
        '''</summary>
        Friend Shared ReadOnly Property Titulo_BU() As String
            Get
                Return ResourceManager.GetString("Titulo_BU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Seleccione desde donde desea restaurar la copia de seguridad.
        '''</summary>
        Friend Shared ReadOnly Property Titulo_RS() As String
            Get
                Return ResourceManager.GetString("Titulo_RS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Todos.
        '''</summary>
        Friend Shared ReadOnly Property Todos() As String
            Get
                Return ResourceManager.GetString("Todos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Total A Cobrar Para El Cliente: $.
        '''</summary>
        Friend Shared ReadOnly Property Total_Cobro() As String
            Get
                Return ResourceManager.GetString("Total_Cobro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Código Postal de la Dirección de Correo.
        '''</summary>
        Friend Shared ReadOnly Property ttCod_Post() As String
            Get
                Return ResourceManager.GetString("ttCod_Post", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CUIT de la Empresa o Identificador Fiscal Similar.
        '''</summary>
        Friend Shared ReadOnly Property ttCUIT() As String
            Get
                Return ResourceManager.GetString("ttCUIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Direccion postal.
        '''</summary>
        Friend Shared ReadOnly Property ttDireccion() As String
            Get
                Return ResourceManager.GetString("ttDireccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Documento Nacional de Identidad o Similar.
        '''</summary>
        Friend Shared ReadOnly Property ttDNI() As String
            Get
                Return ResourceManager.GetString("ttDNI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dirección de Correo Electrónico.
        '''</summary>
        Friend Shared ReadOnly Property ttEmail() As String
            Get
                Return ResourceManager.GetString("ttEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Estado Civil del empleado..
        '''</summary>
        Friend Shared ReadOnly Property ttEstado() As String
            Get
                Return ResourceManager.GetString("ttEstado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Localidad de la Ciudad.
        '''</summary>
        Friend Shared ReadOnly Property ttLocalidad() As String
            Get
                Return ResourceManager.GetString("ttLocalidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Detalles de Cuenta No Pertenecientes al Cliente.
        '''</summary>
        Friend Shared ReadOnly Property ttNoCliente() As String
            Get
                Return ResourceManager.GetString("ttNoCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre del Cliente.
        '''</summary>
        Friend Shared ReadOnly Property ttNombreC() As String
            Get
                Return ResourceManager.GetString("ttNombreC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre del Usuario del sistema.
        '''</summary>
        Friend Shared ReadOnly Property ttNombreU() As String
            Get
                Return ResourceManager.GetString("ttNombreU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nro. de Cuenta Corriente.
        '''</summary>
        Friend Shared ReadOnly Property ttNroCuenta() As String
            Get
                Return ResourceManager.GetString("ttNroCuenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Profesión o cargo que ejerce la persona.
        '''</summary>
        Friend Shared ReadOnly Property ttOcupacion() As String
            Get
                Return ResourceManager.GetString("ttOcupacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a País al que pertenece la determinada provincia.
        '''</summary>
        Friend Shared ReadOnly Property ttPais() As String
            Get
                Return ResourceManager.GetString("ttPais", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Provincia o Estado de Residencia.
        '''</summary>
        Friend Shared ReadOnly Property ttProvincia() As String
            Get
                Return ResourceManager.GetString("ttProvincia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Detalles de Cuenta Pertenecientes al Cliente.
        '''</summary>
        Friend Shared ReadOnly Property ttSiCliente() As String
            Get
                Return ResourceManager.GetString("ttSiCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Número de sucursal donde trabaja el empleado..
        '''</summary>
        Friend Shared ReadOnly Property ttSucursal() As String
            Get
                Return ResourceManager.GetString("ttSucursal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Numero de Telefono.
        '''</summary>
        Friend Shared ReadOnly Property ttTelefono() As String
            Get
                Return ResourceManager.GetString("ttTelefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tipo de Telefono (Fijo,Celular,Laboral,Fax,etc).
        '''</summary>
        Friend Shared ReadOnly Property ttTipotel() As String
            Get
                Return ResourceManager.GetString("ttTipotel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Unidad de Medida.
        '''</summary>
        Friend Shared ReadOnly Property Unidad_Medida() As String
            Get
                Return ResourceManager.GetString("Unidad_Medida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuario.
        '''</summary>
        Friend Shared ReadOnly Property Usuario() As String
            Get
                Return ResourceManager.GetString("Usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ventanas.
        '''</summary>
        Friend Shared ReadOnly Property Ventanas() As String
            Get
                Return ResourceManager.GetString("Ventanas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ventas.
        '''</summary>
        Friend Shared ReadOnly Property Ventas() As String
            Get
                Return ResourceManager.GetString("Ventas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ver.
        '''</summary>
        Friend Shared ReadOnly Property Ver() As String
            Get
                Return ResourceManager.GetString("Ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vertical.
        '''</summary>
        Friend Shared ReadOnly Property Vertical() As String
            Get
                Return ResourceManager.GetString("Vertical", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
