'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class resIngles
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Capa3_Seguridad_Servicios.resIngles", GetType(resIngles).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Client Management.
        '''</summary>
        Friend Shared ReadOnly Property ABMCliente() As String
            Get
                Return ResourceManager.GetString("ABMCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Familiy  Management.
        '''</summary>
        Friend Shared ReadOnly Property ABMFamilia() As String
            Get
                Return ResourceManager.GetString("ABMFamilia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patent Management.
        '''</summary>
        Friend Shared ReadOnly Property ABMPatente() As String
            Get
                Return ResourceManager.GetString("ABMPatente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User Management.
        '''</summary>
        Friend Shared ReadOnly Property ABMUsuario() As String
            Get
                Return ResourceManager.GetString("ABMUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Accept.
        '''</summary>
        Friend Shared ReadOnly Property Aceptar() As String
            Get
                Return ResourceManager.GetString("Aceptar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a About ....
        '''</summary>
        Friend Shared ReadOnly Property Acercade() As String
            Get
                Return ResourceManager.GetString("Acercade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Status: Activated.
        '''</summary>
        Friend Shared ReadOnly Property Activado() As String
            Get
                Return ResourceManager.GetString("Activado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Activate.
        '''</summary>
        Friend Shared ReadOnly Property Activar() As String
            Get
                Return ResourceManager.GetString("Activar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Activity.
        '''</summary>
        Friend Shared ReadOnly Property Actividad() As String
            Get
                Return ResourceManager.GetString("Actividad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Update.
        '''</summary>
        Friend Shared ReadOnly Property Actualizar() As String
            Get
                Return ResourceManager.GetString("Actualizar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administration.
        '''</summary>
        Friend Shared ReadOnly Property Administracion() As String
            Get
                Return ResourceManager.GetString("Administracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Manage Database.
        '''</summary>
        Friend Shared ReadOnly Property AdministrarBD() As String
            Get
                Return ResourceManager.GetString("AdministrarBD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Add  &gt;&gt;.
        '''</summary>
        Friend Shared ReadOnly Property Agregar() As String
            Get
                Return ResourceManager.GetString("Agregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Food.
        '''</summary>
        Friend Shared ReadOnly Property Alimento() As String
            Get
                Return ResourceManager.GetString("Alimento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;&lt; Previous.
        '''</summary>
        Friend Shared ReadOnly Property Anterior() As String
            Get
                Return ResourceManager.GetString("Anterior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Last Name.
        '''</summary>
        Friend Shared ReadOnly Property Apellido() As String
            Get
                Return ResourceManager.GetString("Apellido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Assign .
        '''</summary>
        Friend Shared ReadOnly Property Asignar() As String
            Get
                Return ResourceManager.GetString("Asignar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Automatic.
        '''</summary>
        Friend Shared ReadOnly Property Automatico() As String
            Get
                Return ResourceManager.GetString("Automatico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Help.
        '''</summary>
        Friend Shared ReadOnly Property Ayuda() As String
            Get
                Return ResourceManager.GetString("Ayuda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Backup.
        '''</summary>
        Friend Shared ReadOnly Property Backup() As String
            Get
                Return ResourceManager.GetString("Backup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a State Bar.
        '''</summary>
        Friend Shared ReadOnly Property BEstado() As String
            Get
                Return ResourceManager.GetString("BEstado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tool Bar.
        '''</summary>
        Friend Shared ReadOnly Property BHerramientas() As String
            Get
                Return ResourceManager.GetString("BHerramientas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Logs.
        '''</summary>
        Friend Shared ReadOnly Property Bitacora() As String
            Get
                Return ResourceManager.GetString("Bitacora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Search &gt;&gt;.
        '''</summary>
        Friend Shared ReadOnly Property Buscar() As String
            Get
                Return ResourceManager.GetString("Buscar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Search Customer Status Checks.
        '''</summary>
        Friend Shared ReadOnly Property Buscar_Estado() As String
            Get
                Return ResourceManager.GetString("Buscar_Estado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change Password.
        '''</summary>
        Friend Shared ReadOnly Property Cambiar() As String
            Get
                Return ResourceManager.GetString("Cambiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel.
        '''</summary>
        Friend Shared ReadOnly Property Cancelar() As String
            Get
                Return ResourceManager.GetString("Cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel New.
        '''</summary>
        Friend Shared ReadOnly Property Cancelar_Nuevo() As String
            Get
                Return ResourceManager.GetString("Cancelar_Nuevo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Quantity.
        '''</summary>
        Friend Shared ReadOnly Property Cantidad() As String
            Get
                Return ResourceManager.GetString("Cantidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Caracteristics.
        '''</summary>
        Friend Shared ReadOnly Property Caracteristicas() As String
            Get
                Return ResourceManager.GetString("Caracteristicas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Charge.
        '''</summary>
        Friend Shared ReadOnly Property Cargo() As String
            Get
                Return ResourceManager.GetString("Cargo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cascade.
        '''</summary>
        Friend Shared ReadOnly Property Cascada() As String
            Get
                Return ResourceManager.GetString("Cascada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Categories.
        '''</summary>
        Friend Shared ReadOnly Property Categorias() As String
            Get
                Return ResourceManager.GetString("Categorias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Close.
        '''</summary>
        Friend Shared ReadOnly Property Cerrar() As String
            Get
                Return ResourceManager.GetString("Cerrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Logout.
        '''</summary>
        Friend Shared ReadOnly Property Cerrar_Sesion() As String
            Get
                Return ResourceManager.GetString("Cerrar_Sesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a For the Client.
        '''</summary>
        Friend Shared ReadOnly Property CheckCliente() As String
            Get
                Return ResourceManager.GetString("CheckCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Not fot the Client.
        '''</summary>
        Friend Shared ReadOnly Property CheckNoCliente() As String
            Get
                Return ResourceManager.GetString("CheckNoCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cash Checks.
        '''</summary>
        Friend Shared ReadOnly Property Cheque_C() As String
            Get
                Return ResourceManager.GetString("Cheque_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Clients.
        '''</summary>
        Friend Shared ReadOnly Property Cliente() As String
            Get
                Return ResourceManager.GetString("Cliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Check cashing.
        '''</summary>
        Friend Shared ReadOnly Property Cobrar_Cheque() As String
            Get
                Return ResourceManager.GetString("Cobrar_Cheque", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Payment.
        '''</summary>
        Friend Shared ReadOnly Property Cobro() As String
            Get
                Return ResourceManager.GetString("Cobro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Check Code.
        '''</summary>
        Friend Shared ReadOnly Property Cod_Cheque() As String
            Get
                Return ResourceManager.GetString("Cod_Cheque", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Account Code.
        '''</summary>
        Friend Shared ReadOnly Property Cod_Cuenta() As String
            Get
                Return ResourceManager.GetString("Cod_Cuenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Zip Code.
        '''</summary>
        Friend Shared ReadOnly Property Cod_Post() As String
            Get
                Return ResourceManager.GetString("Cod_Post", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Coments.
        '''</summary>
        Friend Shared ReadOnly Property Comentarios() As String
            Get
                Return ResourceManager.GetString("Comentarios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Compresion.
        '''</summary>
        Friend Shared ReadOnly Property Comprimir() As String
            Get
                Return ResourceManager.GetString("Comprimir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ticket.
        '''</summary>
        Friend Shared ReadOnly Property Comprobante() As String
            Get
                Return ResourceManager.GetString("Comprobante", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Concept.
        '''</summary>
        Friend Shared ReadOnly Property Concepto() As String
            Get
                Return ResourceManager.GetString("Concepto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Condition.
        '''</summary>
        Friend Shared ReadOnly Property Condicion() As String
            Get
                Return ResourceManager.GetString("Condicion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Configurations.
        '''</summary>
        Friend Shared ReadOnly Property Configuraciones() As String
            Get
                Return ResourceManager.GetString("Configuraciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Search.
        '''</summary>
        Friend Shared ReadOnly Property Consulta() As String
            Get
                Return ResourceManager.GetString("Consulta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contents.
        '''</summary>
        Friend Shared ReadOnly Property Contenido() As String
            Get
                Return ResourceManager.GetString("Contenido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password.
        '''</summary>
        Friend Shared ReadOnly Property Contrasena() As String
            Get
                Return ResourceManager.GetString("Contrasena", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Controls.
        '''</summary>
        Friend Shared ReadOnly Property Controles() As String
            Get
                Return ResourceManager.GetString("Controles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Copy.
        '''</summary>
        Friend Shared ReadOnly Property Copiar() As String
            Get
                Return ResourceManager.GetString("Copiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Amount.
        '''</summary>
        Friend Shared ReadOnly Property Costo() As String
            Get
                Return ResourceManager.GetString("Costo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Criticality.
        '''</summary>
        Friend Shared ReadOnly Property Criticidad() As String
            Get
                Return ResourceManager.GetString("Criticidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Account.
        '''</summary>
        Friend Shared ReadOnly Property Cuentas() As String
            Get
                Return ResourceManager.GetString("Cuentas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Status: Deactivated.
        '''</summary>
        Friend Shared ReadOnly Property Desactivado() As String
            Get
                Return ResourceManager.GetString("Desactivado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Deactivate.
        '''</summary>
        Friend Shared ReadOnly Property Desactivar() As String
            Get
                Return ResourceManager.GetString("Desactivar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description.
        '''</summary>
        Friend Shared ReadOnly Property Descripcion() As String
            Get
                Return ResourceManager.GetString("Descripcion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a From.
        '''</summary>
        Friend Shared ReadOnly Property Desde() As String
            Get
                Return ResourceManager.GetString("Desde", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Detail.
        '''</summary>
        Friend Shared ReadOnly Property Detalle() As String
            Get
                Return ResourceManager.GetString("Detalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Account Details.
        '''</summary>
        Friend Shared ReadOnly Property DetallesCuenta() As String
            Get
                Return ResourceManager.GetString("DetallesCuenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sales Details.
        '''</summary>
        Friend Shared ReadOnly Property DetalleVentas() As String
            Get
                Return ResourceManager.GetString("DetalleVentas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Address.
        '''</summary>
        Friend Shared ReadOnly Property Direccion() As String
            Get
                Return ResourceManager.GetString("Direccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Check Digit.
        '''</summary>
        Friend Shared ReadOnly Property DV() As String
            Get
                Return ResourceManager.GetString("DV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Age.
        '''</summary>
        Friend Shared ReadOnly Property Edad() As String
            Get
                Return ResourceManager.GetString("Edad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Edit.
        '''</summary>
        Friend Shared ReadOnly Property Edicion() As String
            Get
                Return ResourceManager.GetString("Edicion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete.
        '''</summary>
        Friend Shared ReadOnly Property Eliminar() As String
            Get
                Return ResourceManager.GetString("Eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a E-Mail.
        '''</summary>
        Friend Shared ReadOnly Property EMail() As String
            Get
                Return ResourceManager.GetString("EMail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Employee.
        '''</summary>
        Friend Shared ReadOnly Property Empleado() As String
            Get
                Return ResourceManager.GetString("Empleado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contact to the System Administrator.
        '''</summary>
        Friend Shared ReadOnly Property Err_Adm() As String
            Get
                Return ResourceManager.GetString("Err_Adm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a An error was found in the DB. Table/Register :.
        '''</summary>
        Friend Shared ReadOnly Property Err_BD() As String
            Get
                Return ResourceManager.GetString("Err_BD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a There are blank fields:.
        '''</summary>
        Friend Shared ReadOnly Property Err_Blanco() As String
            Get
                Return ResourceManager.GetString("Err_Blanco", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No match is found by field: .
        '''</summary>
        Friend Shared ReadOnly Property Err_Busqueda() As String
            Get
                Return ResourceManager.GetString("Err_Busqueda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The format is invalid or the guy waiting for the field:.
        '''</summary>
        Friend Shared ReadOnly Property Err_Campo() As String
            Get
                Return ResourceManager.GetString("Err_Campo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The Quantity must be greater than 1.
        '''</summary>
        Friend Shared ReadOnly Property Err_Cantidad() As String
            Get
                Return ResourceManager.GetString("Err_Cantidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Unable to perform the operation because the database is open. See your administrator.
        '''</summary>
        Friend Shared ReadOnly Property Err_Conexion() As String
            Get
                Return ResourceManager.GetString("Err_Conexion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error.
        '''</summary>
        Friend Shared ReadOnly Property Err_Elim_Empl() As String
            Get
                Return ResourceManager.GetString("Err_Elim_Empl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error deleting Family.
        '''</summary>
        Friend Shared ReadOnly Property Err_Elim_Fam() As String
            Get
                Return ResourceManager.GetString("Err_Elim_Fam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Already exists:.
        '''</summary>
        Friend Shared ReadOnly Property Err_Existe() As String
            Get
                Return ResourceManager.GetString("Err_Existe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Your new password not match, try again.
        '''</summary>
        Friend Shared ReadOnly Property Err_PassN() As String
            Get
                Return ResourceManager.GetString("Err_PassN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Your actual password is different.
        '''</summary>
        Friend Shared ReadOnly Property Err_PassV() As String
            Get
                Return ResourceManager.GetString("Err_PassV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a There is an error in the Data Base when the system try to read/write. Call the Admnistrator.
        '''</summary>
        Friend Shared ReadOnly Property Err_SQL() As String
            Get
                Return ResourceManager.GetString("Err_SQL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The user already belongs to a family.
        '''</summary>
        Friend Shared ReadOnly Property Err_Usu_Fam() As String
            Get
                Return ResourceManager.GetString("Err_Usu_Fam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a There is already into the Database an User called : .
        '''</summary>
        Friend Shared ReadOnly Property Err_usuario() As String
            Get
                Return ResourceManager.GetString("Err_usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password Error.
        '''</summary>
        Friend Shared ReadOnly Property Error_Reing_Pass() As String
            Get
                Return ResourceManager.GetString("Error_Reing_Pass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Not Defined Error.
        '''</summary>
        Friend Shared ReadOnly Property Error1() As String
            Get
                Return ResourceManager.GetString("Error1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure you want to close the form?.
        '''</summary>
        Friend Shared ReadOnly Property Esperar() As String
            Get
                Return ResourceManager.GetString("Esperar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Status.
        '''</summary>
        Friend Shared ReadOnly Property Estado() As String
            Get
                Return ResourceManager.GetString("Estado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Event.
        '''</summary>
        Friend Shared ReadOnly Property Evento() As String
            Get
                Return ResourceManager.GetString("Evento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Examine.
        '''</summary>
        Friend Shared ReadOnly Property Examinar() As String
            Get
                Return ResourceManager.GetString("Examinar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Operation successful.
        '''</summary>
        Friend Shared ReadOnly Property Exito() As String
            Get
                Return ResourceManager.GetString("Exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Family.
        '''</summary>
        Friend Shared ReadOnly Property Familia() As String
            Get
                Return ResourceManager.GetString("Familia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Date.
        '''</summary>
        Friend Shared ReadOnly Property Fecha() As String
            Get
                Return ResourceManager.GetString("Fecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Date of Hired.
        '''</summary>
        Friend Shared ReadOnly Property Fecha_Ing() As String
            Get
                Return ResourceManager.GetString("Fecha_Ing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Birth Date.
        '''</summary>
        Friend Shared ReadOnly Property Fecha_Nac() As String
            Get
                Return ResourceManager.GetString("Fecha_Nac", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Finances.
        '''</summary>
        Friend Shared ReadOnly Property Finanzas() As String
            Get
                Return ResourceManager.GetString("Finanzas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Until.
        '''</summary>
        Friend Shared ReadOnly Property Hasta() As String
            Get
                Return ResourceManager.GetString("Hasta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tools.
        '''</summary>
        Friend Shared ReadOnly Property Herramientas() As String
            Get
                Return ResourceManager.GetString("Herramientas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hour.
        '''</summary>
        Friend Shared ReadOnly Property Hora() As String
            Get
                Return ResourceManager.GetString("Hora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ID Code.
        '''</summary>
        Friend Shared ReadOnly Property ID() As String
            Get
                Return ResourceManager.GetString("ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change Lenguaje.
        '''</summary>
        Friend Shared ReadOnly Property Idioma_Cambiar() As String
            Get
                Return ResourceManager.GetString("Idioma_Cambiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Lenguaje.
        '''</summary>
        Friend Shared ReadOnly Property Idioma_Text() As String
            Get
                Return ResourceManager.GetString("Idioma_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Print.
        '''</summary>
        Friend Shared ReadOnly Property Imprimir() As String
            Get
                Return ResourceManager.GetString("Imprimir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Index.
        '''</summary>
        Friend Shared ReadOnly Property Indice() As String
            Get
                Return ResourceManager.GetString("Indice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sales revenue.
        '''</summary>
        Friend Shared ReadOnly Property Ingresos() As String
            Get
                Return ResourceManager.GetString("Ingresos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Login.
        '''</summary>
        Friend Shared ReadOnly Property Iniciar_Sesion() As String
            Get
                Return ResourceManager.GetString("Iniciar_Sesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Clear.
        '''</summary>
        Friend Shared ReadOnly Property Limpiar() As String
            Get
                Return ResourceManager.GetString("Limpiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Checks List.
        '''</summary>
        Friend Shared ReadOnly Property Listado_Cheque() As String
            Get
                Return ResourceManager.GetString("Listado_Cheque", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a List.
        '''</summary>
        Friend Shared ReadOnly Property Listar() As String
            Get
                Return ResourceManager.GetString("Listar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a City.
        '''</summary>
        Friend Shared ReadOnly Property Localidad() As String
            Get
                Return ResourceManager.GetString("Localidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Monthly.
        '''</summary>
        Friend Shared ReadOnly Property Mensual() As String
            Get
                Return ResourceManager.GetString("Mensual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Member Of:.
        '''</summary>
        Friend Shared ReadOnly Property MiembroDe() As String
            Get
                Return ResourceManager.GetString("MiembroDe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Amount.
        '''</summary>
        Friend Shared ReadOnly Property Monto() As String
            Get
                Return ResourceManager.GetString("Monto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nickname.
        '''</summary>
        Friend Shared ReadOnly Property Nick() As String
            Get
                Return ResourceManager.GetString("Nick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name.
        '''</summary>
        Friend Shared ReadOnly Property Nombre() As String
            Get
                Return ResourceManager.GetString("Nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Account Number.
        '''</summary>
        Friend Shared ReadOnly Property NroCuenta() As String
            Get
                Return ResourceManager.GetString("NroCuenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New.
        '''</summary>
        Friend Shared ReadOnly Property Nuevo() As String
            Get
                Return ResourceManager.GetString("Nuevo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Number.
        '''</summary>
        Friend Shared ReadOnly Property Numero() As String
            Get
                Return ResourceManager.GetString("Numero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Job.
        '''</summary>
        Friend Shared ReadOnly Property Ocupacion() As String
            Get
                Return ResourceManager.GetString("Ocupacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Backup Finished OK.
        '''</summary>
        Friend Shared ReadOnly Property OK_Backup() As String
            Get
                Return ResourceManager.GetString("OK_Backup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you Sure to change the Lenguaje?.
        '''</summary>
        Friend Shared ReadOnly Property OK_Idioma() As String
            Get
                Return ResourceManager.GetString("OK_Idioma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure to change your password?.
        '''</summary>
        Friend Shared ReadOnly Property OK_Password() As String
            Get
                Return ResourceManager.GetString("OK_Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Restore Finished OK.
        '''</summary>
        Friend Shared ReadOnly Property OK_Restore() As String
            Get
                Return ResourceManager.GetString("OK_Restore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Options.
        '''</summary>
        Friend Shared ReadOnly Property Opciones() As String
            Get
                Return ResourceManager.GetString("Opciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Country.
        '''</summary>
        Friend Shared ReadOnly Property Pais() As String
            Get
                Return ResourceManager.GetString("Pais", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New Password:.
        '''</summary>
        Friend Shared ReadOnly Property Pass_Nuevo() As String
            Get
                Return ResourceManager.GetString("Pass_Nuevo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Actual Password:.
        '''</summary>
        Friend Shared ReadOnly Property Pass_Viejo() As String
            Get
                Return ResourceManager.GetString("Pass_Viejo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Privilegies.
        '''</summary>
        Friend Shared ReadOnly Property Patentes() As String
            Get
                Return ResourceManager.GetString("Patentes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure ?.
        '''</summary>
        Friend Shared ReadOnly Property Preg_Eliminar() As String
            Get
                Return ResourceManager.GetString("Preg_Eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure?.
        '''</summary>
        Friend Shared ReadOnly Property Preg_Opera() As String
            Get
                Return ResourceManager.GetString("Preg_Opera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Preview.
        '''</summary>
        Friend Shared ReadOnly Property Preview() As String
            Get
                Return ResourceManager.GetString("Preview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Processes.
        '''</summary>
        Friend Shared ReadOnly Property Procesos() As String
            Get
                Return ResourceManager.GetString("Procesos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Products.
        '''</summary>
        Friend Shared ReadOnly Property Productos() As String
            Get
                Return ResourceManager.GetString("Productos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a State.
        '''</summary>
        Friend Shared ReadOnly Property Provincia() As String
            Get
                Return ResourceManager.GetString("Provincia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a This is a project developed for the Trabajo de Diploma chair&apos;s in the career of computer-systems engineering in the Universidad Abierta Americana..
        '''</summary>
        Friend Shared ReadOnly Property Proyecto() As String
            Get
                Return ResourceManager.GetString("Proyecto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Purchase and Sell Product System. Forbidden distribution without the consent of the creative enterprise..
        '''</summary>
        Friend Shared ReadOnly Property PurchaseAndSell() As String
            Get
                Return ResourceManager.GetString("PurchaseAndSell", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;&lt; Remove.
        '''</summary>
        Friend Shared ReadOnly Property Quitar() As String
            Get
                Return ResourceManager.GetString("Quitar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Register.
        '''</summary>
        Friend Shared ReadOnly Property Registrar() As String
            Get
                Return ResourceManager.GetString("Registrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sells Record.
        '''</summary>
        Friend Shared ReadOnly Property RegistroVentas() As String
            Get
                Return ResourceManager.GetString("RegistroVentas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reenter Password: .
        '''</summary>
        Friend Shared ReadOnly Property Rein_Pass() As String
            Get
                Return ResourceManager.GetString("Rein_Pass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Database repair succesfully.
        '''</summary>
        Friend Shared ReadOnly Property ReparacionBD() As String
            Get
                Return ResourceManager.GetString("ReparacionBD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Report of .
        '''</summary>
        Friend Shared ReadOnly Property Reporte() As String
            Get
                Return ResourceManager.GetString("Reporte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Staff Report.
        '''</summary>
        Friend Shared ReadOnly Property ReporteEmpleados() As String
            Get
                Return ResourceManager.GetString("ReporteEmpleados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Products Report.
        '''</summary>
        Friend Shared ReadOnly Property ReporteProductos() As String
            Get
                Return ResourceManager.GetString("ReporteProductos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reports.
        '''</summary>
        Friend Shared ReadOnly Property Reportes() As String
            Get
                Return ResourceManager.GetString("Reportes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reservation.
        '''</summary>
        Friend Shared ReadOnly Property Reserva() As String
            Get
                Return ResourceManager.GetString("Reserva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Restore.
        '''</summary>
        Friend Shared ReadOnly Property Restore() As String
            Get
                Return ResourceManager.GetString("Restore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Exit.
        '''</summary>
        Friend Shared ReadOnly Property Salir() As String
            Get
                Return ResourceManager.GetString("Salir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Security.
        '''</summary>
        Friend Shared ReadOnly Property Seguridad() As String
            Get
                Return ResourceManager.GetString("Seguridad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select.
        '''</summary>
        Friend Shared ReadOnly Property Seleccionar() As String
            Get
                Return ResourceManager.GetString("Seleccionar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Branch Address.
        '''</summary>
        Friend Shared ReadOnly Property SucursalDir() As String
            Get
                Return ResourceManager.GetString("SucursalDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Branch Number.
        '''</summary>
        Friend Shared ReadOnly Property SucursalNro() As String
            Get
                Return ResourceManager.GetString("SucursalNro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Telephone.
        '''</summary>
        Friend Shared ReadOnly Property Telefono() As String
            Get
                Return ResourceManager.GetString("Telefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Phone Type.
        '''</summary>
        Friend Shared ReadOnly Property TipoTel() As String
            Get
                Return ResourceManager.GetString("TipoTel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select where to save the backup.
        '''</summary>
        Friend Shared ReadOnly Property Titulo_BU() As String
            Get
                Return ResourceManager.GetString("Titulo_BU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Seleccione desde donde desea restaurar el BackUp.
        '''</summary>
        Friend Shared ReadOnly Property Titulo_RS() As String
            Get
                Return ResourceManager.GetString("Titulo_RS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a All.
        '''</summary>
        Friend Shared ReadOnly Property Todos() As String
            Get
                Return ResourceManager.GetString("Todos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Total customer receivables: $ .
        '''</summary>
        Friend Shared ReadOnly Property Total_Cobro() As String
            Get
                Return ResourceManager.GetString("Total_Cobro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Zip Code of Mailing Address.
        '''</summary>
        Friend Shared ReadOnly Property ttCod_Post() As String
            Get
                Return ResourceManager.GetString("ttCod_Post", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Identification number for the company.
        '''</summary>
        Friend Shared ReadOnly Property ttCUIT() As String
            Get
                Return ResourceManager.GetString("ttCUIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Address of the person.
        '''</summary>
        Friend Shared ReadOnly Property ttDireccion() As String
            Get
                Return ResourceManager.GetString("ttDireccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Identificacion number for the person.
        '''</summary>
        Friend Shared ReadOnly Property ttDNI() As String
            Get
                Return ResourceManager.GetString("ttDNI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Email Address.
        '''</summary>
        Friend Shared ReadOnly Property ttEmail() As String
            Get
                Return ResourceManager.GetString("ttEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Marital status of the employee..
        '''</summary>
        Friend Shared ReadOnly Property ttEstado() As String
            Get
                Return ResourceManager.GetString("ttEstado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a City of the Person.
        '''</summary>
        Friend Shared ReadOnly Property ttLocalidad() As String
            Get
                Return ResourceManager.GetString("ttLocalidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Details of non-Customer Account.
        '''</summary>
        Friend Shared ReadOnly Property ttNoCliente() As String
            Get
                Return ResourceManager.GetString("ttNoCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Member Name for the System.
        '''</summary>
        Friend Shared ReadOnly Property ttNombreC() As String
            Get
                Return ResourceManager.GetString("ttNombreC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User Name for the system.
        '''</summary>
        Friend Shared ReadOnly Property ttNombreU() As String
            Get
                Return ResourceManager.GetString("ttNombreU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nro. de Cuenta Corriente.
        '''</summary>
        Friend Shared ReadOnly Property ttNroCuenta() As String
            Get
                Return ResourceManager.GetString("ttNroCuenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Occupation or position of the individual exercising.
        '''</summary>
        Friend Shared ReadOnly Property ttOcupacion() As String
            Get
                Return ResourceManager.GetString("ttOcupacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Country to which the particular province.
        '''</summary>
        Friend Shared ReadOnly Property ttPais() As String
            Get
                Return ResourceManager.GetString("ttPais", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a State of the Person.
        '''</summary>
        Friend Shared ReadOnly Property ttProvincia() As String
            Get
                Return ResourceManager.GetString("ttProvincia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Account Details Customer Belonging.
        '''</summary>
        Friend Shared ReadOnly Property ttSiCliente() As String
            Get
                Return ResourceManager.GetString("ttSiCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Number of branch where the employee works..
        '''</summary>
        Friend Shared ReadOnly Property ttSucursal() As String
            Get
                Return ResourceManager.GetString("ttSucursal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Number of the telephone.
        '''</summary>
        Friend Shared ReadOnly Property ttTelefono() As String
            Get
                Return ResourceManager.GetString("ttTelefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Type of telephone.
        '''</summary>
        Friend Shared ReadOnly Property ttTipoTel() As String
            Get
                Return ResourceManager.GetString("ttTipoTel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User.
        '''</summary>
        Friend Shared ReadOnly Property Usuario() As String
            Get
                Return ResourceManager.GetString("Usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Windows.
        '''</summary>
        Friend Shared ReadOnly Property Ventanas() As String
            Get
                Return ResourceManager.GetString("Ventanas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sells.
        '''</summary>
        Friend Shared ReadOnly Property Ventas() As String
            Get
                Return ResourceManager.GetString("Ventas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a View.
        '''</summary>
        Friend Shared ReadOnly Property Ver() As String
            Get
                Return ResourceManager.GetString("Ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vertical.
        '''</summary>
        Friend Shared ReadOnly Property Vertical() As String
            Get
                Return ResourceManager.GetString("Vertical", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
